/*FINAL VERSION2
using directors to select ids and do not delete the 0's
*/

WITH 
COMBINED_TABLE as (
SELECT T.GENRE, T.ID, COALESCE(PROB,0) AS PROB FROM
(SELECT T1.GENRE, T1.ID as ID, T2.PROB FROM 
(SELECT * FROM (SELECT DISTINCT GENRE FROM 
DIRECTOR_GENRE) CROSS JOIN (SELECT DISTINCT ID FROM DIRECTORS)) T1
LEFT JOIN (SELECT D.ID, GENRE, PROB FROM DIRECTOR_GENRE DG INNER JOIN DIRECTORS D ON
DG.DIRECTOR_ID = D.ID) T2
ON T1.ID = T2.ID AND T1.GENRE = T2.GENRE) T
), 

NON_GENRE_TABLE AS (SELECT NO_GENRE_T.ID1, NO_GENRE_T.ID2, COALESCE(PROB,0) AS SUMNUM FROM (
SELECT N1.ID AS ID1, N2.ID AS ID2, N1.PROB FROM
(SELECT ID, PROB FROM (SELECT * FROM DIRECTORS D LEFT JOIN DIRECTOR_GENRE DG ON D.ID = DG.DIRECTOR_ID) 
WHERE GENRE IS NULL) N1, (SELECT ID, GENRE FROM (SELECT * FROM DIRECTORS D LEFT JOIN DIRECTOR_GENRE DG ON D.ID = DG.DIRECTOR_ID) 
WHERE GENRE IS NULL) N2 WHERE N1.ID < N2.ID) NO_GENRE_T),

Finaltable as (SELECT NON_GENRE_TABLE.ID1, NON_GENRE_TABLE.ID2, NON_GENRE_TABLE.SUMNUM FROM NON_GENRE_TABLE
UNION
SELECT FT.ID1, FT.ID2, SUM(FT.ABSP) AS SUMNUM FROM
(
SELECT TT1.ID AS ID1, TT2.ID AS ID2,TT1.PROB AS P1, TT2.PROB AS P2, TT1.GENRE AS GENRE, ABS(TT1.PROB - TT2.PROB) AS ABSP
FROM COMBINED_TABLE TT1, COMBINED_TABLE TT2
WHERE TT1.ID < TT2.ID AND TT1.GENRE = TT2.GENRE AND (TT1.PROB>0 OR TT2.PROB>0)
) FT GROUP BY FT.ID1, FT.ID2)

select * from (select ID1 AS DIRECTOR_ID1, ID2 AS DIRECTOR_ID2 from finaltable order by sumnum,id1, id2) where rownum<=5;


